[package]
name = "enkel-consumer"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enkel = { version = "^0", path = "../.." }
glm = "0.2.3"
env_logger = "0.9.0"